title: Advanced Scratch Sushi Cards
hero_image: images/banner.png
description: Make a platform-style game and add your own levels, powers, and characters.
theme: orange
version: 1
listed: false
copyedit: false
last_tested: "2018-04-23"
steps:
  - title: Introduction
  - title: What you will need
  - title: Setting things up
  - title: Losing the game
  - title: Power-ups
  - title: Super power-ups!
  - title: Adding some competition
  - title: Level 2
  - title: Moving platforms
  - title: What next?
