---
title: Fart catcher
hero_image: images/banner.png
description: Δημιούργησε ένα παιχνίδι σε στυλ πλατφόρμας και πρόσθεσε τα δικά σου επίπεδα, δυνάμεις και χαρακτήρες.
theme: orange
listed: true
copyedit: true
curriculum: ''
interests: ''
technologies: scratch
site_areas: coderdojo, projects
hardware: ''
software: scratch
version: 3.0.0
last_tested: "2018-04-23"
steps:
  - 
    title: Εισαγωγή
  - 
    title: Setting things up
  - 
    title: Χάνοντας το παιχνίδι
  - 
    title: Power-ups
  - 
    title: Super power-ups!
  - 
    title: Adding some competition
  - 
    title: Επίπεδο 2
  - 
    title: Κινούμενες πλατφόρμες
  - 
    title: Και τώρα;
