---
title: Συλλέκτης πορδών
hero_image: images/banner.png
description: Δημιούργησε ένα παιχνίδι σε στυλ πλατφόρμας και πρόσθεσε τα δικά σου
  επίπεδα, δυνάμεις και χαρακτήρες.
theme: orange
listed: true
copyedit: true
curriculum: ''
interests: ''
technologies: scratch
site_areas: coderdojo, projects
hardware: ''
software: scratch
version: 3.0.0
last_tested: '2018-04-23'
steps:
- title: Εισαγωγή
- title: Πρώτες ρυθμίσεις
- title: Χάνοντας το παιχνίδι
  completion:
  - engaged
- title: Βραβεία
- title: Σούπερ Βραβεία!
- title: Προσθήκη ανταγωνισμού
- title: Επίπεδο 2
- title: Κινούμενες πλατφόρμες
  completion:
  - internal
- title: Και τώρα;
